<?php
    $conn = mysqli_connect("localhost", "root", ""); // establishing a connection string....
    
    if($conn) { echo "<br> Successful Connection !"; } // checking if connection is established....
    else {
        echo "<br> Failed Connection !";
        exit(); // exit if connection failed....
    }
    $query = "CREATE DATABASE IF NOT EXISTS college"; // query to create a database....
    $r1 = mysqli_query($conn, $query);
    
    if($r1) { echo "<br> Database created successfully !"; } // checking if query is successfully executed....
    else {
        echo "<br> Database creation failed !";
        exit();
    }
    mysqli_close($conn); // closing connection....
?>